### ISSUE TITLE
Nancy boostrapping occurs during install and uninstall

### ISSUE THREAD

**Issue by jbuedel** [justeat/Topshelf.Nancy#12]
I noticed that my subclass of DefaultNancyBoostrapper is being executed anytime NancyServiceConfiguratorExtensions.WithNancyEndpoint  is called. So basically, every time my TopShelf hosting app is run, including during installs and uninstalls.  In fact, it runs *before* my InstallHostConfiguratorExtensions.BeforeInstall() lambda is even called.

I expected the Nancy bootstrapping to run around the same time as when Topshelf's WhenStarted() was called. This seems like a bug to me. Do you agree, or have any suggestions on how I might do things differently?

**Comment by jbuedel** [comment]
I've created a pull request for this.

https://github.com/justeat/Topshelf.Nancy/pull/13

**Comment by AnthonySteele** [comment]
The PR has been merged. Can we close this issue?
